language: python
build_image: shippableimages/ubuntu1404_python
commit_container: yazgoo/fuse_kafka
before_install:
    - bash -c "[ -z \"${SHIPPABLE}\" ] && ( echo 'deb http://fr.archive.ubuntu.com/ubuntu/ trusty universe' | sudo tee -a /etc/apt/sources.list ) || echo"
    - sudo apt-get -y update -qq
    - ulimit -c unlimited -S
    - sudo apt-get -y install gdb
# prerequisites for tox:
    - sudo add-apt-repository -y ppa:fkrull/deadsnakes
    - sudo apt-get -y update
    - sudo apt-get -y install python2.6 python2.7 python3.3 python3.4 python
    - sudo pip install tox
#    - bash -c "[ -z \"${SHIPPABLE}\" ] && echo || sudo apt-get -y -f install mininet openvswitch-controller openvswitch-common"
#    - bash -c "[ -z \"${SHIPPABLE}\" ] && echo || sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --reinstall linux-image-$(uname -r)"
#    - bash -c "[ -z \"${SHIPPABLE}\" ] && echo || sudo modprobe openvswitch"
install:
    - sed -i 's/_mt/_st/' build.py
    - sudo apt-get -y install python-coverage libfuse-dev librdkafka-dev libjansson-dev libzookeeper-st-dev
    - bash -c "[ -z \"${SHIPPABLE}\" ] || sudo apt-get -y libglib2.0"
    - sudo pip install fabricate cpp-coveralls
script:
    - ./build.py clean
    - ./build.py
    - ./build.py test
    - tox # to test fuse_kafka against multiple python versions
#    - bash -c "[ -z \"${SHIPPABLE}\" ] && echo || sudo ./build.py mininet"
    - sudo ./build.py install
after_failure:
    - find
    - cat /proc/sys/kernel/core_pattern
    - dmesg
    - sudo cat /var/log/messages
    - gdb --batch --quiet -ex "thread apply all bt full" -ex "quit" fuse_kafka.test core*
after_success:
    - bash -c "[ -z \"${SHIPPABLE}\" ] && coveralls --exclude bin --exclude tests --gcov-options '\-lp' || echo"
    - git config --global user.name "${GIT_NAME}"
    - git config --global user.email "${GIT_EMAIL}"
    - mkdir doc
    - cd doc
    - git clone https://github.com/yazgoo/fuse_kafka.git .
    - git checkout gh-pages
    - cd ..
    - sudo apt-get -y install doxygen
    - bash -c "[ -z \"${SHIPPABLE}\" ] && ./build.py doc || echo"
    - cd doc
    - git add --all .
    - bash -c "[ -z \"${SHIPPABLE}\" ] && git commit -m 'auto updating documentation' || echo "
    - bash -c "[ -z \"${SHIPPABLE}\" ] && git push https://${GH_TOKEN}@github.com/yazgoo/fuse_kafka.git gh-pages || echo"
env:
    global:
        secure: LZlIH/SfgTMAQjUULjIk4j6pxhxVKPRvzRopdDeFnXrRozIeBdUUOePQEMoFYiiu/qAhoROEiO9SupvyX6YE2wGpEm/PIN30HmAXN1OxabpADPjyjbCHycaYb8ejl9xjoA3w68YbT7ezhV/ut1fvuihDZxotqUodXK7n1m7M+K4=
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d3c4bddd8542f4a29b44
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
